adding SimpleCov coverage

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,6 +22,7 @@ jobs:
       - name: Scan for common Rails security vulnerabilities using static analysis
         run: bin/brakeman --no-pager
 
+
   run_test:
     runs-on: ubuntu-latest
 
@@ -54,6 +55,20 @@ jobs:
           DB_PASSWORD: postgres
         run: bin/rails db:setup spec
 
+      - name: SimpleCov Report in PR
+        if: success() || failure()
+        uses: shettytejas/simplecov-reporter@v1
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+
+      # Optional: Fail build if coverage is below a threshold
+      - name: Check SimpleCov coverage threshold
+        uses: joshmfrankel/simplecov-check-action@main
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          minimum_suite_coverage: 90
+
+
   lint:
     runs-on: ubuntu-latest
     steps:
@@ -68,4 +83,3 @@ jobs:
 
       - name: Lint code for consistent style
         run: bin/rubocop -f github
-
